apiVersion: oort.ccs.guidewire.com/v1alpha1
kind: GatewayConfig
metadata:
  namespace: ${POD_NAME}
  name: ${APP_NAME}-gateway-config
spec:
  profiles:
    - name: Default
      response_transformer:
        add:
          headers:
            - Content-Security-Policy:frame-ancestors https://*.guidewire.net https://*.guidewire.com
            - X-Frame-Options:SAMEORIGIN
            - Access-Control-Allow-Origin:*
            - Access-Control-Allow-Methods:GET, OPTIONS
            - Access-Control-Allow-Headers:*
  path_configs:
    - name: Default
      paths:
        - /**
      profiles:
        - Default
  service_ref: ${APP_NAME}
  service_alias: docs
  enable_sub_domain: false
