apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: docportal-ingress
  annotations:
    ingress.kubernetes.io/config-backend: |
      http-response add-header Content-Security-Policy \"frame-ancestors https://*.guidewire.net\"
      http-response add-header X-Frame-Options SAMEORIGIN
spec:
  rules:
  - host: docs.guidewire.com
    http:
      paths:
      - backend:
          serviceName: docportal-app
          servicePort: 8081
        path: /
  - host: docs.guidewire.com
    http:
      paths:
      - backend:
          serviceName: docportal-app
          servicePort: 8081
        path: /