apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_NAME}-semantic-search-model-pv-claim-${DEPLOY_ENV}
  namespace: doctools
  labels:
    app: ${APP_NAME}
    gwcp.guidewire.com/dept: \"${DEPT_CODE}\"
    gwcp.guidewire.com/maintained-by: ${POD_NAME}
    gwcp.guidewire.com/created-by: ${POD_NAME}
    gwcp.guidewire.com/tenant-name: ${POD_NAME}
    gwcp.guidewire.com/version: ${TAG_VERSION}
    gwcp.guidewire.com/app-name: ${APP_NAME}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi