yarnPath: .yarn/releases/yarn-3.4.1.cjs
nodeLinker: node-modules
npmAlwaysAuth: true
npmAuthToken: ${NPM_AUTH_TOKEN}
npmScopes:
  doctools:
    npmRegistryServer: https://artifactory.guidewire.com/artifactory/api/npm/doctools-npm-dev/
