compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: "${NPM_AUTH_TOKEN}"

npmScopes:
  doctools:
    npmRegistryServer: "https://artifactory.guidewire.com/artifactory/api/npm/doctools-npm-dev/"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
