package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '26bb0d234633d89b6604d4b7d9842891'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("26bb0d234633d89b6604d4b7d9842891")) {
    params {
        expect {
            text("reverse.dep.DocumentationTools_Development_PawelSKtsExperiments_DocumentationPortalForGithub_f5cca57694b9bba5f59dff3cc64374b2.env.CHANGED_FILES", "db/")
        }
        update {
            select("reverse.dep.DocumentationTools_Development_PawelSKtsExperiments_DocumentationPortalForGithub_f5cca57694b9bba5f59dff3cc64374b2.env.CHANGED_FILES", "db/",
                    allowMultiple = true,
                    options = listOf("db/"))
        }
    }
}
