package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '29fae923318850439fd83d55d1067b54'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("29fae923318850439fd83d55d1067b54")) {
    params {
        expect {
            text("reverse.dep.DocumentationTools_Development_PawelSKtsExperiments_DocumentationPortalForGithub_f5cca57694b9bba5f59dff3cc64374b2.env.CHANGED_FILES", "landing-pages/,core/")
        }
        update {
            select("reverse.dep.DocumentationTools_Development_PawelSKtsExperiments_DocumentationPortalForGithub_f5cca57694b9bba5f59dff3cc64374b2.env.CHANGED_FILES", "landing-pages/,core/",
                    allowMultiple = true,
                    options = listOf("landing-pages/", "core/"))
        }
    }
}
