package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '29fae923318850439fd83d55d1067b54'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("29fae923318850439fd83d55d1067b54")) {
    dependencies {
        expect(RelativeId("d76b3ebe0f4f40b75fa53e789a6a4a0f")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "root-breadcrumbs.json => landing-pages/public"
            }
        }
        update(RelativeId("d76b3ebe0f4f40b75fa53e789a6a4a0f")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "root-breadcrumbs.json => landing-pages/public/root-breadcrumbs.json"
            }
        }

    }
}
