package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '29fae923318850439fd83d55d1067b54'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("29fae923318850439fd83d55d1067b54")) {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
