package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '421aea6d5b0fd2b586d2e56d2f7ca0bd'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("421aea6d5b0fd2b586d2e56d2f7ca0bd")) {
    failureConditions {

        check(executionTimeoutMin == 0) {
            "Unexpected option value: executionTimeoutMin = $executionTimeoutMin"
        }
        executionTimeoutMin = 2880
    }
}
