package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '54f5d04244d30862aecc9f1fb3d99f49'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("54f5d04244d30862aecc9f1fb3d99f49")) {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
