package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '6828629bdb3f8fcdf752ef02784453c1'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("6828629bdb3f8fcdf752ef02784453c1")) {
    check(artifactRules == "") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "%teamcity.build.workingDir%/*.log => build_logs"
}
