package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '9e3a9bb1718006ab9a77447a7d888400'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("9e3a9bb1718006ab9a77447a7d888400")) {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
