package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '9e3a9bb1718006ab9a77447a7d888400'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("9e3a9bb1718006ab9a77447a7d888400")) {
    params {
        expect {
            text("reverse.dep.DocumentationTools_Development_PawelSKtsExperiments_DocumentationPortalForGithub_f5cca57694b9bba5f59dff3cc64374b2.env.CHANGED_FILES", "server/,core/")
        }
        update {
            select("reverse.dep.DocumentationTools_Development_PawelSKtsExperiments_DocumentationPortalForGithub_f5cca57694b9bba5f59dff3cc64374b2.env.CHANGED_FILES", "server/,core/",
                    allowMultiple = true,
                    options = listOf("server/", "core/"))
        }
    }
}
