package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'advancedproductdesignergitbuildslistener'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("advancedproductdesignergitbuildslistener")) {
    vcs {

        check(branchFilter == """
            +:refs/heads/main
            +:refs/heads/release/2021.04
            +:refs/heads/release/2021.11
        """.trimIndent()) {
            "Unexpected option value: branchFilter = $branchFilter"
        }
        branchFilter = "+:release/*"
    }
}
