package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'c9d643e4d602a6e2b286e46bca2d31ce'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("c9d643e4d602a6e2b286e46bca2d31ce")) {
    expectSteps {
        script {
            name = "Run the lion pkg builder"
            scriptContent = """
                #!/bin/bash
                set -xe
                
                export TEAMCITY_API_ROOT_URL="https://gwre-devexp-ci-production-devci.gwre-devops.net/app/rest/" 
                export TEAMCITY_API_AUTH_TOKEN="%env.TEAMCITY_API_ACCESS_TOKEN%"
                export TEAMCITY_RESOURCES_ARTIFACT_PATH="json/build-data.json"
                export ZIP_SRC_DIR="zip"
                export OUTPUT_PATH="out"
                export WORKING_DIR="%teamcity.build.checkoutDir%"
                export TC_BUILD_TYPE_ID="DocumentationTools_DocPortal_86dd8b937e4c8ae48ad16077227e31ff"
                
                lion_pkg_builder
            """.trimIndent()
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerImage = "artifactory.guidewire.com/doctools-docker-dev/lion-pkg-builder:latest"
        }
        script {
            name = "Add build data"
            scriptContent = """
                #!/bin/bash
                set -xe
                
                mkdir _builds
                jq -n '{"root": "b_data-studio.ditamap", "filter": "GW-Generic-EA-Release.ditaval"}' > _builds/datastudiorelease.json
                zip -ur %teamcity.build.checkoutDir%/out/l10n_package.zip _builds
            """.trimIndent()
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            clearConditions()
            scriptContent = """
                #!/bin/bash
                set -xe
                
                mkdir _builds
                jq -n '{"root": "b_data-studio.ditamap", "filter": "GW-Generic-EA-Release.ditaval"}' > _builds/datastudiorelease.json
                zip -ur %teamcity.build.checkoutDir%/out/l10n_package.zip _builds app_guide/graphics/videos/Introduction-to-DataStudio-script-v4.srt
            """.trimIndent()
        }
    }
}
