package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'DeployProd'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("DeployProd")) {
    params {
        remove {
            param("env.AWS_SECRET_ACCESS_KEY", "credentialsJSON:8c32ef05-72e7-4262-ad01-59e17cf3b48c")
        }
    }
}
