package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'DeployProd'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("DeployProd")) {
    params {
        remove {
            param("env.ATMOS_PROD_AWS_DEFAULT_REGION", "us-west-2")
        }
        remove {
            param("env.AWS_ACCESS_KEY_ID", "credentialsJSON:12f70400-8b00-4bac-a368-f7d68bc99fa7")
        }
        remove {
            param("env.AWS_DEFAULT_REGION", "%env.ATMOS_PROD_AWS_DEFAULT_REGION%")
        }
        remove {
            param("env.AWS_SECRET_ACCESS_KEY", "credentialsJSON:8c32ef05-72e7-4262-ad01-59e17cf3b48c")
        }
    }
}
