package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.triggers.VcsTrigger
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'docguidesrcvalidationlistener'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("docguidesrcvalidationlistener")) {
    triggers {
        val trigger1 = find<VcsTrigger> {
            vcs {
            }
        }
        trigger1.apply {
            enabled = false

        }
    }

    features {
        val feature1 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                publisher = bitbucketServer {
                    url = "https://stash.guidewire.com"
                    userName = "%env.BITBUCKET_SERVICE_ACCOUNT_USERNAME%"
                    password = "%env.BITBUCKET_ACCESS_TOKEN%"
                }
            }
        }
        feature1.apply {
            publisher = bitbucketServer {
                url = "https://stash.guidewire.com"
                userName = "%env.BITBUCKET_SERVICE_ACCOUNT_USERNAME%"
                password = "credentialsJSON:28000373-d3ae-4957-878b-a52ae604781a"
            }
        }
        val feature2 = find<PullRequests> {
            pullRequests {
                provider = bitbucketServer {
                    serverUrl = "https://stash.guidewire.com"
                    authType = token {
                        token = "%env.BITBUCKET_ACCESS_TOKEN%"
                    }
                    filterTargetBranch = "+:refs/heads/main"
                }
            }
        }
        feature2.apply {
            provider = bitbucketServer {
                serverUrl = "https://stash.guidewire.com"
                authType = token {
                    token = "credentialsJSON:28000373-d3ae-4957-878b-a52ae604781a"
                }
                filterSourceBranch = ""
                filterTargetBranch = "+:refs/heads/main"
            }
        }
    }
}
