package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PublishthemetoArtifactory'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PublishthemetoArtifactory")) {
    expectSteps {
        script {
            name = "NPM publish theme"
            scriptContent = """
                npm install -g npm-cli-login
                npm-cli-login -u ${'$'}{ARTIFACTORY_SERVICE_ACCOUNT_USERNAME} -p ${'$'}{ARTIFACTORY_API_KEY} -e svc-doc-artifactory@guidewire.com -r https://artifactory.guidewire.com/api/npm/doctools-npm-dev
                npm config set @doctools:registry https://artifactory.guidewire.com/api/npm/doctools-npm-dev/
                npm config set always-auth true
                npm config set unsafe-perm true
                
                yarn install
                yarn build:theme
                cd docusaurus/themes/gw-theme-classic
                npm publish
            """.trimIndent()
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerImage = "artifactory.guidewire.com/hub-docker-remote/node:16.16.0"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = """
                npm config set @doctools:registry https://artifactory.guidewire.com/api/npm/doctools-npm-dev/
                npm config set always-auth true
                npm config set unsafe-perm true
                
                yarn install
                yarn build:theme
                cd docusaurus/themes/gw-theme-classic
                npm publish
            """.trimIndent()
        }
    }
}
