package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Publishtostagingstandards202206jaJP'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Publishtostagingstandards202206jaJP")) {
    expectSteps {
        script {
            name = "Upload content to the S3 bucket"
            id = "UPLOAD_CONTENT_TO_THE_S3_BUCKET"
            scriptContent = """
                #!/bin/bash
                                    set -xe
                                    
                                    export AWS_ACCESS_KEY_ID="%env.ATMOS_DEV_AWS_ACCESS_KEY_ID%"
                export AWS_SECRET_ACCESS_KEY="%env.ATMOS_DEV_AWS_SECRET_ACCESS_KEY%"
                export AWS_DEFAULT_REGION="%env.ATMOS_DEV_AWS_DEFAULT_REGION%"
                                    
                                    aws s3 sync "%teamcity.build.checkoutDir%/out" s3://tenant-doctools-staging-builds/cloud/standards/ja-JP/202206 --delete
            """.trimIndent()
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerImage = "artifactory.guidewire.com/devex-docker-dev/atmosdeploy:2.6.0"
            dockerRunParameters = "-v /var/run/docker.sock:/var/run/docker.sock -v ${'$'}pwd:/app:ro"
        }
        script {
            name = "Get config file"
            id = "GET_CONFIG_FILE"
            scriptContent = """
                #!/bin/bash
                set -xe
                
                export CONFIG_FILE="%teamcity.build.workingDir%/config.json"
                export TMP_CONFIG_FILE="%teamcity.build.workingDir%/tmp_config.json"
                export CONFIG_FILE_URL="https://docportal-content.staging.ccs.guidewire.net/portal-config/config.json"
                
                curl ${'$'}CONFIG_FILE_URL > ${'$'}TMP_CONFIG_FILE
                
                if [[ "staging" == "prod" ]]; then
                    cat ${'$'}TMP_CONFIG_FILE | jq -r '{"docs": [.docs[] | select(.url | startswith("portal/secure/doc") | not)]}' > ${'$'}CONFIG_FILE                 
                elif [[ "staging" == "portal2" ]]; then
                    cat ${'$'}TMP_CONFIG_FILE | jq -r '{"docs": [.docs[] | select(.url | startswith("portal/secure/doc"))]}' > ${'$'}CONFIG_FILE
                else
                    cat ${'$'}TMP_CONFIG_FILE > ${'$'}CONFIG_FILE
                fi
            """.trimIndent()
        }
        script {
            name = "Run the doc crawler"
            id = "RUN_THE_DOC_CRAWLER"
            scriptContent = """
                #!/bin/bash
                set -xe
                
                export CONFIG_FILE="%teamcity.build.workingDir%/config.json"
                export DOC_ID="standards202206jaJP"
                export DOC_S3_URL="https://docportal-content.staging.ccs.guidewire.net"
                export ELASTICSEARCH_URLS="https://docsearch-doctools.staging.ccs.guidewire.net"
                export APP_BASE_URL="https://docs.staging.ccs.guidewire.net"
                export DOCS_INDEX_NAME="gw-docs"
                export BROKEN_LINKS_INDEX_NAME="broken-links"
                export SHORT_TOPICS_INDEX_NAME="short-topics"
                export REPORT_BROKEN_LINKS="yes"
                export REPORT_SHORT_TOPICS="yes"
                
                cat > scrapy.cfg <<- EOM
                [settings]
                default = doc_crawler.settings
                EOM
                
                doc_crawler
            """.trimIndent()
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerImage = "artifactory.guidewire.com/doctools-docker-dev/doc-crawler:latest"
        }
        script {
            name = "Build the html5 output"
            id = "BUILD_THE_HTML5_OUTPUT"
            scriptContent = """
                #!/bin/bash
                                set -xe
                                
                                export EXIT_CODE=0
                                SECONDS=0
                                
                                echo "Downloading the ditaval file from common-gw submodule"
                                    
                export COMMON_GW_DITAVALS_DIR="%teamcity.build.checkoutDir%/common_gw_ditavals"
                mkdir -p ${'$'}COMMON_GW_DITAVALS_DIR && cd ${'$'}COMMON_GW_DITAVALS_DIR 
                curl -O https://stash.guidewire.com/rest/api/1.0/projects/DOCSOURCES/repos/common-gw/raw/ditavals/GW-Generic-Release.ditaval \
                    -H "Accept: application/json" \
                    -H "Authorization: Bearer %env.BITBUCKET_ACCESS_TOKEN%"
                
                                echo "Building output"
                                dita -i "%teamcity.build.checkoutDir%/surepath.ditamap" -o "%teamcity.build.checkoutDir%/out" --processing-mode "strict" --filter "%teamcity.build.checkoutDir%/common_gw_ditavals/GW-Generic-Release.ditaval" --gw-base-url "cloud/standards/ja-JP/202206" --gw-doc-id "standards202206jaJP" --gw-doc-title "Guidewire Cloud Standards ja-JP" --generate.build.data "yes" --git.url "ssh://git@stash.guidewire.com/docsources/standards.git" --git.branch "build/ja-JP/2022.06" -f "html5-Guidewire" --args.rellinks "nofamily" --build.pdfs "yes" --create-index-redirect "yes" || EXIT_CODE=${'$'}?
                                
                                duration=${'$'}SECONDS
                                echo "BUILD FINISHED AFTER ${'$'}((${'$'}duration / 60)) minutes and ${'$'}((${'$'}duration % 60)) seconds"
                                exit ${'$'}EXIT_CODE
            """.trimIndent()
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerImage = "artifactory.guidewire.com/doctools-docker-dev/dita-ot:3.6.1"
        }
    }
    steps {
        insert(0) {
            script {
                name = "Build the html5 output"
                id = "BUILD_THE_HTML5_OUTPUT"
                scriptContent = """
                    #!/bin/bash
                                    set -xe
                                    
                                    export EXIT_CODE=0
                                    SECONDS=0
                                    
                                    echo "Downloading the ditaval file from common-gw submodule"
                                        
                    export COMMON_GW_DITAVALS_DIR="%teamcity.build.checkoutDir%/common_gw_ditavals"
                    mkdir -p ${'$'}COMMON_GW_DITAVALS_DIR && cd ${'$'}COMMON_GW_DITAVALS_DIR 
                    curl -O https://stash.guidewire.com/rest/api/1.0/projects/DOCSOURCES/repos/common-gw/raw/ditavals/GW-Generic-Release.ditaval \
                        -H "Accept: application/json" \
                        -H "Authorization: Bearer %env.BITBUCKET_ACCESS_TOKEN%"
                    
                                    echo "Building output"
                                    dita -i "%teamcity.build.checkoutDir%/surepath.ditamap" -o "%teamcity.build.checkoutDir%/out" --processing-mode "strict" --filter "%teamcity.build.checkoutDir%/common_gw_ditavals/GW-Generic-Release.ditaval" --gw-base-url "cloud/standards/ja-JP/202206" --gw-doc-id "standards202206jaJP" --gw-doc-title "Guidewire Cloud Standards ja-JP" --generate.build.data "yes" --git.url "ssh://git@stash.guidewire.com/docsources/standards.git" --git.branch "build/ja-JP/2022.06" -f "html5-Guidewire" --args.rellinks "nofamily" --build.pdfs "yes" --create-index-redirect "yes" || EXIT_CODE=${'$'}?
                                    
                                    duration=${'$'}SECONDS
                                    echo "BUILD FINISHED AFTER ${'$'}((${'$'}duration / 60)) minutes and ${'$'}((${'$'}duration % 60)) seconds"
                                    exit ${'$'}EXIT_CODE
                """.trimIndent()
                dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
                dockerImage = "artifactory.guidewire.com/doctools-docker-dev/dita-ot:3.6.1"
            }
        }
        items.removeAt(4)
    }
}
