package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.dockerSupport
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PublishthemetoArtifactory'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PublishthemetoArtifactory")) {
    features {
        remove {
            dockerSupport {
                loginToRegistry = on {
                    dockerRegistryId = "PROJECT_EXT_155"
                }
            }
        }
    }
}
