apiVersion: apps/v1
kind: Deployment
metadata:
  name: docportal-app-deployment
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: docportal-app
  replicas: 1
  template:
    metadata:
      labels:
        app: docportal-app
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::627188849628:role/aws_gwre-ccs-dev_tenant_doctools_developer
    spec:
      containers:
      - name: docportal
        image: artifactory.guidewire.com/doctools-docker-dev/docportal:${TAG_VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /alive
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 45
        readinessProbe:
          httpGet:
            path: /alive
            port: 8081
          initialDelaySeconds: 150
          periodSeconds: 45
        env:
        - name: REFRESH_IMAGE
          value: 'BUILD_TIME'
        - name: OKTA_DOMAIN
          value: ${OKTA_DOMAIN}
        - name: OKTA_CLIENT_ID
          value: ${OKTA_CLIENT_ID}
        - name: OKTA_CLIENT_SECRET
          value: ${OKTA_CLIENT_SECRET}
        - name: APP_BASE_URL
          value: https://docportal-${NAMESPACE}.${DEPLOY_ENV}.ccs.guidewire.net
        - name: SESSION_KEY
          value: ${SESSION_KEY}
        - name: ELASTIC_SEARCH_URL
          value: https://docsearch-doctools.${DEPLOY_ENV}.ccs.guidewire.net
        - name: DOC_S3_URL
          value: https://ditaot.internal.${DEPLOY_ENV}.ccs.guidewire.net
        - name: ZIPKIN_URL
          value: https://zipkin.internal.${DEPLOY_ENV}.ccs.guidewire.net/api/v2/spans
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
      imagePullSecrets:
      - name: artifactory-secret