FROM artifactory.guidewire.com/hub-docker-remote/nginx

COPY isconfigupgradetools /usr/share/nginx/html/isconfigupgradetools
COPY assets /usr/share/nginx/html/assets
COPY index.html /usr/share/nginx/html/index.html
COPY portal-config /usr/share/nginx/html/portal-config