package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = '54afdfe83a6bd49be1b4264baac80739_virtual'
in the project with id = '54afdfe83a6bd49be1b4264baac80739', and delete the patch script.
*/
create(RelativeId("54afdfe83a6bd49be1b4264baac80739"), Project({
    id("54afdfe83a6bd49be1b4264baac80739_virtual")
    name = "Update ja (iscc202402jaJPupdate) (auto-generated)"
}))

