package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "JetBrains.SharedResources"
                id = "PROJECT_EXT_2450"
                param("quota", "3")
                param("name", "OxygenWebhelpLicense")
                param("type", "quoted")
            }
        }
    }
}
