package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.activeStorage
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'standards202206jaJP'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("standards202206jaJP")) {
    features {
        add {
            activeStorage {
                id = "PROJECT_EXT_368"
                activeStorageID = "DefaultStorage"
            }
        }
    }
}
