package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'insurancesuiteconfigurationupgradetools3xgit'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("insurancesuiteconfigurationupgradetools3xgit")) {
    val expected = GitVcsRoot({
        id("insurancesuiteconfigurationupgradetools3xgit")
        name = "insurancesuiteconfigurationupgradetools3xgit"
        url = "ssh://git@stash.guidewire.com/docsources/insurancesuite-configuration-upgrade-tools-3x.git"
        branch = "refs/heads/master"
        branchSpec = "+:*"
        checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.USE_MIRRORS
        authMethod = uploadedKey {
            uploadedKey = "sys-doc.rsa"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branchSpec = ""
    }

}
