package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'isupgradeguide202111srcValidationbuilds_DocumentationToolsDocumentationPortalIsupgradeguide202111src'
in the project with id = 'isupgradeguide202111srcValidationbuilds', and delete the patch script.
*/
create(RelativeId("isupgradeguide202111srcValidationbuilds"), GitVcsRoot({
    id("isupgradeguide202111srcValidationbuilds_DocumentationToolsDocumentationPortalIsupgradeguide202111src")
    name = "DocumentationTools_DocumentationPortal_isupgradeguide202111src"
    url = "ssh://git@stash.guidewire.com/docsources/insurancesuite-upgrade-guide.git"
    branch = "refs/heads/release/2022.05"
    checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.USE_MIRRORS
    authMethod = uploadedKey {
        uploadedKey = "sys-doc.rsa"
    }
}))

