apiVersion: v1
kind: ConfigMap
metadata:
  name: docsearch-app-config-${DEPLOY_ENV}
  namespace: doctools
data:
  discovery_type: single-node
  xpack_security_enabled: 'false'
  cluster_name: es-${DEPLOY_ENV}
  elasticsearch.yml: |
    cluster.name: es-${DEPLOY_ENV}
    network.host: 0.0.0.0
    path.data: /usr/share/elasticsearch/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docsearch-pv-claim-${DEPLOY_ENV}
  namespace: doctools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docsearch-${DEPLOY_ENV}
  namespace: doctools
spec:
  selector:
    matchLabels:
      app: docsearch-${DEPLOY_ENV}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docsearch-${DEPLOY_ENV}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: docsearch-${DEPLOY_ENV}
          image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: \"4G\"
              cpu: \"1\"
            limits:
              memory: \"8G\"
              cpu: \"2\"
          env:
            - name: discovery.type
              valueFrom:
                configMapKeyRef:
                  name: docsearch-app-config-${DEPLOY_ENV}
                  key: discovery_type
            - name: xpack.security.enabled
              valueFrom:
                configMapKeyRef:
                  name: docsearch-app-config-${DEPLOY_ENV}
                  key: xpack_security_enabled
            - name: cluster_name
              valueFrom:
                configMapKeyRef:
                  name: docsearch-app-config-${DEPLOY_ENV}
                  key: cluster_name
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-storage
            - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              name: docsearch-app-config-${DEPLOY_ENV}
              subPath: elasticsearch.yml

      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: docsearch-pv-claim-${DEPLOY_ENV}
        - name: docsearch-app-config-${DEPLOY_ENV}
          configMap:
            name: docsearch-app-config-${DEPLOY_ENV}
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
---
apiVersion: v1
kind: Service
metadata:
  name: docsearch-${DEPLOY_ENV}
  namespace: doctools
  labels:
    app: docsearch-${DEPLOY_ENV}
spec:
  type: ClusterIP
  selector:
    app: docsearch-${DEPLOY_ENV}
  ports:
    - name: http
      port: 9200
      protocol: TCP
    - name: transport
      port: 9300
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: doctools
  name: docsearch-ingress-${DEPLOY_ENV}
spec:
  rules:
    - host: docsearch-doctools.internal.${DEPLOY_ENV}.service.guidewire.net
      http:
        paths:
          - backend:
              service:
                name: docsearch-${DEPLOY_ENV}
                port:
                  number: 9200
            path: /
            pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-doctools-${DEPLOY_ENV}
  namespace: doctools
  labels:
    component: kibana
spec:
  ports:
    - port: 5601
  selector:
    component: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-doctools-${DEPLOY_ENV}
  namespace: doctools
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.16.3
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://docsearch-${DEPLOY_ENV}:9200
          ports:
            - containerPort: 5601
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: doctools
  name: kibana-doctools-ingress-${DEPLOY_ENV}
spec:
  rules:
    - host: kibana-doctools.internal.${DEPLOY_ENV}.service.guidewire.net
      http:
        paths:
          - backend:
              service:
                name: kibana-doctools-${DEPLOY_ENV}
                port:
                  number: 5601
            path: /
            pathType: Prefix
