import { FilterConfig } from './ChatFilter';

export const filtersFromDb: FilterConfig[] = [
  {
    label: 'Product',
    name: 'product',
    values: [
      'DataHub',
      'PolicyCenter',
      'InsuranceNow',
      'ClaimCenter',
      'InfoCenter',
      'BillingCenter',
      'Digital Reference Applications',
      'Guidewire Cloud Home',
      'Internal Docs',
      'Predict',
      'InsuranceSuite Configuration Upgrade Tools',
      'Advanced Product Designer',
      'Analytics Manager Solution Templates',
      'App Events Webhooks',
      'Explore',
      'Global Content',
      'Product Adoption',
      'Compare',
      'Workflow Service',
      'Jutro Design System',
      'Jutro Digital Platform',
      'Canvas',
      'Cloud Standards',
      'Cloud Platform',
      'Lifecycle Manager',
      'Community Case Templates',
      'Guidewire AppReader',
      'Submission Intake',
      'Data Platform',
      'Workset Manager',
      'Rules',
    ],
  },
  {
    label: 'Version',
    name: 'version',
    values: [
      '2023.2',
      '2023.06',
      '4.5.0',
      '4.4.0',
      '2023.3',
      '2023.1',
      '2021.2',
      '2022.1',
      '2022.2',
      '2022.09',
      '2023.02',
      '2023.10',
      '2022.05',
      '10.0',
      '2021.04',
      '10.2.2',
      '10.2.1',
      '2021.11',
      'Innsbruck',
      '8.10.0 LTS',
      '4.6.0',
      '4.2.0',
      '4.0.0',
      '3.3.0',
      '4.3.0',
      '4.1.0',
      '5.1.0',
      '5.0.0',
      'Hakuba',
      '2023.12',
      'latest',
      '2021.1',
    ],
  },
  {
    label: 'Release',
    name: 'release',
    values: [
      'Garmisch',
      'Hakuba',
      'Innsbruck',
      'Flaine',
      'Elysian',
      'Dobson',
      'Cortina',
    ],
  },
  {
    label: 'Subject',
    name: 'subject',
    values: [
      'Configuration',
      'Administration',
      'Testing',
      'Release notes',
      'Best practices',
      'Features and functionality',
      'Glossary',
      'Integration',
      'Development',
      'Upgrade',
      'Installation',
    ],
  },
  { label: 'Platform', name: 'platform', values: ['Self-managed', 'Cloud'] },
];
