apiVersion: v1
kind: ConfigMap
metadata:
  name: docsearch-app-config
  namespace: doctools
data:
  discovery_type: single-node
  cluster_name: es-dev
  elasticsearch.yml: |
    cluster.name: es-dev
    network.host: 0.0.0.0
    path.data: /usr/share/elasticsearch/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docsearch-app-pv-claim
  namespace: doctools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docsearch
  namespace: doctools
spec:
  selector:
    matchLabels:
      app: docsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: docsearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: docsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
          imagePullPolicy: IfNotPresent
          env:
            - name: discovery.type
              valueFrom:
                configMapKeyRef:
                  name: docsearch-app-config
                  key: discovery_type
            - name: cluster_name
              valueFrom:
                configMapKeyRef:
                  name: docsearch-app-config
                  key: cluster_name
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-storage
            - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              name: docsearch-app-config
              subPath: elasticsearch.yml

      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: docsearch-app-pv-claim
        - name: docsearch-app-config
          configMap:
            name: docsearch-app-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
---
apiVersion: v1
kind: Service
metadata:
  name: docsearch
  namespace: doctools
  labels:
    app: docsearch
spec:
  type: ClusterIP
  selector:
    app: docsearch
  ports:
    - name: http
      port: 9200
      protocol: TCP
    - name: transport
      port: 9300
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: doctools
  name: docsearch-ingress
spec:
  rules:
  - host: docsearch-doctools.dev.ccs.guidewire.net
    http:
      paths:
      - backend:
          serviceName: docsearch
          servicePort: 9200
        path: /