[tool.poetry]
name = "dita_processor"
version = "0.1.0"
description = ""
authors = ["Guidewire"]
license = "LGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
