version: '3.8'
services:
  server:
    networks:
      - docportal_network
    image: artifactory.guidewire.com/hub-docker-remote/node:18.18.2
    container_name: server
    restart: always
    environment:
      - NODE_ENV=development
      - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
    ports:
      - "8081:8081"
    volumes:
      - ..:/usr/app
    working_dir: /usr/app
    command: yarn server-dev
    depends_on:
      - db
  landing-pages:
    networks:
      - docportal_network
    image: artifactory.guidewire.com/hub-docker-remote/node:18.18.2
    container_name: landing-pages
    restart: always
    environment:
      - NODE_ENV=development
      - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
    ports:
      - "6006:6006"
    volumes:
      - ..:/usr/app
    working_dir: /usr/app
    command: yarn landing-pages-dev
  db:
    networks:
      - docportal_network
    image: artifactory.guidewire.com/hub-docker-remote/postgres:13.9-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testtesttest
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  search:
    networks:
      - docportal_network
    image: artifactory.guidewire.com/hub-docker-remote/elasticsearch:7.17.4
    container_name: search
    environment:
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - search_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
networks:
  docportal_network:
    driver: bridge
volumes:
  db_volume:
  search_volume:
