package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'BuildDocSiteOutputFromDita'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("BuildDocSiteOutputFromDita")) {
    features {
        add {
            feature {
                id = "BUILD_EXT_857"
                type = "JetBrains.SharedResources"
                param("locks-param", "OxygenWebhelpLicense readLock")
            }
        }
    }
}
