import { VersionSelectorProps } from '@theme/VersionSelector';

export const versionSelectorMockup: VersionSelectorProps[] = [
  {
    versions: ['8.6.0'],
    releases: null,
    url: '#',
    label: '8.6.0',
  },
  {
    versions: ['2021.2'],
    releases: null,
    url: '#',
    label: '2021.2',
  },
  {
    versions: ['2021.4'],
    releases: ['Banff'],
    url: '#',
    label: '2021.4 (Cortina)',
  },
  {
    versions: ['8.5.0'],
    releases: null,
    url: '#',
    label: '8.5.0',
  },
  {
    versions: ['8.4.0'],
    releases: null,
    url: '#',
    label: '8.4.0',
  },
  {
    versions: ['8.3.2'],
    releases: null,
    url: '#',
    label: '8.3.2',
  },
  {
    versions: ['8.2.0'],
    releases: null,
    url: '#',
    label: '8.2.0',
  },
  {
    versions: ['8.1.0'],
    releases: null,
    url: '#',
    label: '8.1.0',
  },
  {
    versions: ['8.0.0'],
    releases: null,
    url: '#',
    label: '8.0.0',
  },
  {
    versions: ['7.5.0'],
    releases: null,
    url: '#',
    label: '7.5.0',
  },
  {
    versions: ['7.3.0'],
    releases: null,
    url: '#',
    label: '7.3.0',
  },
  {
    versions: ['7.2.0'],
    releases: null,
    url: '#',
    label: '7.2.0',
  },
  {
    versions: ['7.1.1'],
    releases: null,
    url: '#',
    label: '7.1.1',
  },
  {
    versions: ['7.0.0'],
    releases: null,
    url: '#',
    label: '7.0.0',
  },
  {
    versions: ['6.6.0'],
    releases: null,
    url: '#',
    label: '6.6.0',
  },
  {
    versions: ['6.4.0'],
    releases: null,
    url: '#',
    label: '6.4.0',
  },
  {
    versions: ['6.3.0'],
    releases: null,
    url: '#',
    label: '6.3.0',
  },
  {
    versions: ['6.2.0'],
    releases: null,
    url: '#',
    label: '6.2.0',
  },
  {
    versions: ['6.1.0'],
    releases: null,
    url: '#',
    label: '6.1.0',
  },
  {
    versions: ['6.0.0'],
    releases: null,
    url: '#',
    label: '6.0.0',
  },
  {
    versions: ['5.4.0'],
    releases: null,
    url: '#',
    label: '5.4.0',
  },
  {
    versions: ['5.3.1'],
    releases: null,
    url: '#',
    label: '5.3.1',
  },
  {
    versions: ['5.2.0'],
    releases: null,
    url: '#',
    label: '5.2.0',
  },
  {
    versions: ['5.1.0'],
    releases: null,
    url: '#',
    label: '5.1.0',
  },
  {
    versions: ['5.0.0'],
    releases: null,
    url: '#',
    label: '5.0.0',
  },
  {
    versions: ['4.3.0'],
    releases: null,
    url: '#',
    label: '4.3.0',
  },
  {
    versions: ['4.2.1'],
    releases: null,
    url: '#',
    label: '4.2.1',
  },
  {
    versions: ['4.1.1'],
    releases: ['Banff'],
    url: '#',
    label: '4.1.1',
  },
  {
    versions: ['8.6.0 (latest)'],
    releases: null,
    url: '#',
    currentlySelected: true,
    label: '8.6.0 (latest)',
  },
  {
    versions: ['8.3.0 LTS'],
    releases: ['Flaine'],
    url: '#',
    label: '8.3.0 LTS',
  },
  {
    versions: ['7.4.3 LTS'],
    releases: ['Elysian'],
    url: '#',
    label: '7.4.3 LTS',
  },
  {
    versions: ['6.5.2 LTS'],
    releases: ['Dobson'],
    url: '#',
    label: '6.5.2 LTS',
  },
  {
    versions: ['5.3.2 LTS'],
    releases: ['Cortina'],
    url: '#',
    label: '5.3.2 LTS',
  },
];
